name = "sutte"
main = "worker.js"
compatibility_date = "2026-03-02"

[vars]
DEFAULT_SCOPE = "public_repo"

# Secrets:
#   wrangler secret put GITHUB_CLIENT_ID
#   wrangler secret put GITHUB_CLIENT_SECRET
